### ISSUE TITLE
lab: Locks <buffer cache>

### ISSUE THREAD

**Issue by fjc-hub** [Echomo-Xinyu/xv6-2023-mit-labs#1]
bget()函数应该有并发问题，检查哈希桶cache miss后立即释放了对应的桶锁，后续没有检查原哈希桶中是否被其他线程添加了对应的entry就直接头插法插入哈希桶，容易插入相同的block吧

**Comment by Echomo-Xinyu** [comment]
距离我写这个代码有一段时间了，我粗略看了一下感觉没有问题？
“检查 block 是否被cache，如果被cache 那返还带锁block；如果没有被cache，获得当前bcache bucket的锁后寻找一个没有被使用的 block。”如果别的线程正在添加对应的entry，那在这之前无法获得对应的锁。如果别的线程已经完成添加了，那我查验refcnt 为0即说明不再使用，refcnt 不为0也就不会被改写，因此refcnt为0就可以替换掉当前内容了。
我觉得正确性上没有问题，还是你在讨论效率的问题？

**Comment by fjc-hub** [comment]
> 距离我写这个代码有一段时间了，我粗略看了一下感觉没有问题？ “检查 block 是否被cache，如果被cache 那返还带锁block；如果没有被cache，获得当前bcache bucket的锁后寻找一个没有被使用的 block。”如果别的线程正在添加对应的entry，那在这之前无法获得对应的锁。如果别的线程已经完成添加了，那我查验refcnt 为0即说明不再使用，refcnt 不为0也就不会被改写，因此refcnt为0就可以替换掉当前内容了。 我觉得正确性上没有问题，还是你在讨论效率的问题？

新增这里看着没有再次检查哈希桶里面有没有被其他线程添加相同的block吧？
![image](https://github.com/user-attachments/assets/eff68ce0-e2a1-403b-8653-045d8abeb428)

**Comment by Echomo-Xinyu** [comment]
嗯嗯，你说得对。我当时写的时候想的是增加颗粒度，只在用锁的时候拿着锁，想了一下不会死锁就这么写了。确实存在浪费的情况，效率确实低了一些，虽然不影响正确性，谢谢指正。
